[package]
name = "map-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rrt = { path = "../rrt" }
nalgebra = { version = "^0.29" }